// ============================================================
// RepeaterMock Mirror — Dynamic catalog
//
// Instead of a static SERIES array, this loads the list of scraped
// tests dynamically by fetching /tests/index.json (generated by
// the scraper). Only fully-scraped tests (questions + answers +
// solutions + analysis) are listed in /tests/index.json.
//
// If index.json is missing (first run, no tests scraped yet), the
// home page shows an empty state with a link to the dashboard.
// ============================================================

let _SERIES_CACHE = null;
let _TESTS_CACHE = null;

// 53 target series — used to map test_id → series name even before scraping
const TARGET_SERIES = [
  { platform: "tb",     slug: "ssc-cgl",                                       name: "SSC CGL Mock Test Series 2026 (Tier I & Tier II) PYQs" },
  { platform: "tb-pro", slug: "ssc-cgl",                                       name: "SSC CGL Mock Test Series 2026 (Tier I & Tier II)" },
  { platform: "gd",     slug: "ssc-selection-post",                            name: "SSC Selection Post" },
  { platform: "gd",     slug: "sbi-po",                                        name: "SBI PO" },
  { platform: "gd",     slug: "ssc-cgl",                                       name: "SSC CGL Free" },
  { platform: "tb",     slug: "rrb-group-d",                                   name: "RRB Group D Mock Test Series 2025-26 (New) PYQs" },
  { platform: "tb-pro", slug: "rrb-group-d",                                   name: "RRB Group D Mock Test Series 2025-26 (New)" },
  { platform: "tb",     slug: "ssc-maths-previous-year-questions",             name: "SSC Maths PYP Mock Test Series (20k+ Questions) PYQs" },
  { platform: "tb-pro", slug: "ssc-maths-previous-year-questions",             name: "SSC Maths PYP Mock Test Series (20k+ Questions)" },
  { platform: "tb",     slug: "ssc-reasoning-previous-year-questions",         name: "SSC Reasoning PYP Mock Test Series (20k+ Questions) PYQs" },
  { platform: "tb-pro", slug: "ssc-reasoning-previous-year-questions",         name: "SSC Reasoning PYP Mock Test Series (20k+ Questions)" },
  { platform: "gd",     slug: "ssc-cpo",                                       name: "SSC CPO" },
  { platform: "tb",     slug: "ssc-chsl",                                      name: "SSC CHSL Mock Test Series 2026 (Tier I & Tier II) PYQs" },
  { platform: "tb-pro", slug: "ssc-chsl",                                      name: "SSC CHSL Mock Test Series 2026 (Tier I & Tier II)" },
  { platform: "gd",     slug: "ssc-cgl-previous-year-paper",                   name: "SSC CGL Previous Year Paper" },
  { platform: "tb",     slug: "ssc-english-previous-year-questions",           name: "SSC English PYP Mock Test Series (20k+ Questions) PYQs" },
  { platform: "tb-pro", slug: "ssc-english-previous-year-questions",           name: "SSC English PYP Mock Test Series (20k+ Questions)" },
  { platform: "tb",     slug: "ssc-mts",                                       name: "SSC MTS & Havaldar Mock Test Series 2026 PYQs" },
  { platform: "gd",     slug: "ssc-mts",                                       name: "SSC MTS" },
  { platform: "tb-pro", slug: "ssc-mts",                                       name: "SSC MTS & Havaldar Mock Test Series 2026" },
  { platform: "gd",     slug: "ssc-chsl",                                      name: "SSC CHSL" },
  { platform: "tb",     slug: "ssc-gk-previous-year-questions",                name: "SSC GK PYP Mock Test Series (20k+ Questions) PYQs" },
  { platform: "tb-pro", slug: "ssc-gk-previous-year-questions",                name: "SSC GK PYP Mock Test Series (20k+ Questions)" },
  { platform: "gd",     slug: "ssc-gd",                                        name: "SSC GD" },
  { platform: "tb-pro", slug: "ssc-stenographer",                              name: "SSC Stenographer Grade C & D Mock Test 2026 (New Pattern)" },
  { platform: "gd",     slug: "ssc-delhi-head-constable",                      name: "SSC Delhi Head Constable" },
  { platform: "tb",     slug: "ssc-stenographer",                              name: "SSC Stenographer Grade C & D Mock Test 2026 (New Pattern) PYQs" },
  { platform: "tb",     slug: "ssc-selection-post",                            name: "SSC Selection Post (Phase 14) 2026 Mock Test Series PYQs" },
  { platform: "tb-pro", slug: "ssc-cpo-ranker",                                name: "SSC CPO Rankers Test Series 2025" },
  { platform: "tb",     slug: "ssc-gd-constable",                              name: "SSC GD Constable 2026 Mock Test Series PYQs" },
  { platform: "tb-pro", slug: "ssc-selection-post",                            name: "SSC Selection Post (Phase 14) 2026 Mock Test Series" },
  { platform: "tb",     slug: "ssc-cpo",                                       name: "SSC CPO Mock Test Series 2026 (Tier I & II) PYQs" },
  { platform: "tb",     slug: "ssc-chsl-previous",                             name: "SSC CHSL Mock Test Series 2025 (Tier I & Tier II) PYQs" },
  { platform: "tb-pro", slug: "ssc-cpo",                                       name: "SSC CPO Mock Test Series 2026 (Tier I & II)" },
  { platform: "tb",     slug: "ssc-cpo-previous",                              name: "SSC CPO Mock Test Series 2025 (Tier I & II) (DP SI & CAPF) (New Pattern) PYQs" },
  { platform: "tb-pro", slug: "ssc-chsl-previous",                             name: "SSC CHSL Mock Test Series 2025 (Tier I & Tier II)" },
  { platform: "tb",     slug: "ssc-je-ce",                                     name: "SSC JE Civil 2026 Mock Test (Paper 1 & Paper 2) PYQs" },
  { platform: "tb-pro", slug: "ssc-cpo-previous",                              name: "SSC CPO Mock Test Series 2025 (Tier I & II) (DP SI & CAPF) (New Pattern)" },
  { platform: "tb",     slug: "ssc-mts-previous",                              name: "SSC MTS & Havaldar Mock Test Series 2025 PYQs" },
  { platform: "tb-pro", slug: "ssc-je-ce",                                     name: "SSC JE Civil 2026 Mock Test (Paper 1 & Paper 2)" },
  { platform: "tb",     slug: "ssc-je-ee",                                     name: "SSC JE Electrical 2026 Mock Test (Paper 1 & Paper 2) PYQs" },
  { platform: "tb-pro", slug: "ssc-mts-previous",                              name: "SSC MTS & Havaldar Mock Test Series 2025" },
  { platform: "tb",     slug: "west-bengal-group-c",                           name: "WB SSC Group C & D Combined Mock Test Series 2025 PYQs" },
  { platform: "tb-pro", slug: "west-bengal-group-c",                           name: "WB SSC Group C & D Combined Mock Test Series 2025" },
  { platform: "tb-pro", slug: "rrb-maths-previous-year-questions",             name: "Mathematics for All Railway Exams Previous Year Paper Mock Test" },
  { platform: "tb",     slug: "rrb-gk-previous-year-questions",                name: "General Knowledge for All Railway Exams Previous Year Paper Mock Test PYQs" },
  { platform: "tb-pro", slug: "rrb-reasoning-previous-year-questions",         name: "Reasoning for All Railway Exams Previous Year Paper Mock Test" },
  { platform: "tb",     slug: "rrb-general-science-previous-year-questions",   name: "General Science for All Railway Exams Previous Year Paper Mock Test PYQs" },
  { platform: "tb-pro", slug: "rrb-gk-previous-year-questions",                name: "General Knowledge for All Railway Exams Previous Year Paper Mock Test" },
  { platform: "tb-pro", slug: "rrb-general-science-previous-year-questions",   name: "General Science for All Railway Exams Previous Year Paper Mock Test" },
  { platform: "tb-pro", slug: "general-knowledge-ssc-railways-competitive-exams", name: "Ace General Knowledge - For All Railway, SSC & Other Competitive Exams" },
  { platform: "tb-pro", slug: "ssc-railways-polity",                           name: "Polity Master Pack for SSC / Railways / State Exams" },
  { platform: "tb",     slug: "general-knowledge-ssc-railways-competitive-exams", name: "Ace General Knowledge - For All Railway, SSC & Other Competitive Exams" },
];

const REPEATERMOCK_INSTRUCTIONS = {
  general: [
    "The clock will be set at the server. The countdown timer at the top right corner of screen will display the remaining time available for you to complete the examination. When the timer reaches zero, the examination will end by itself.",
    "The Question Palette displayed on the right side of screen will show the status of each question using one of the following symbols: You have not visited the question yet; You have not answered the question; You have answered the question; You have NOT answered the question, but have marked it for review; You have answered the question, but marked it for review. The Mark For Review status simply indicates that you would like to look at that question again. If a question is answered but marked for review, the answer will be considered for evaluation."
  ],
  navigating: [
    "Click on the question number in the Question Palette to go to that question directly. This does NOT save your answer.",
    "Click Save & Next to save your answer and go to the next question.",
    "Click Mark for Review & Next to save, mark for review, and proceed."
  ],
  navigatingNote: "You can view all the questions by clicking on the Question Paper button. This feature is provided so that you can see the entire question paper at a glance.",
  answering: [
    "Procedure for answering a multiple choice (MCQ) question: Choose one answer from options A, B, C, D and click the bubble. To deselect, click the bubble again or click Clear Response. To change your answer, click on another option. To save, you MUST click Save & Next.",
    "Procedure for answering a numerical answer type question: Enter a number using the virtual numerical keypad. A fraction (e.g. -0.3) can be entered with or without \"0\" before the decimal point. Up to four decimal places can be entered. Click Clear Response to clear your answer. To save, you MUST click Save & Next.",
    "Note that ONLY questions for which answers are saved or marked for review after answering will be considered for evaluation."
  ]
};

// ─── Series → URL helpers ──────────────────────────────────────────────────

function seriesIdFor(platform, slug) {
  return platform + "_" + slug;
}

function seriesUrlFor(platform, slug) {
  return "https://repeatermock.com/" + platform + "/test-series/" + slug;
}

function findSeriesMetaByTestId(testId) {
  // Look up the test in the loaded tests list
  if (!_TESTS_CACHE) return null;
  for (const t of _TESTS_CACHE) {
    if (t.test_id === testId) return t;
  }
  return null;
}

// ─── Dynamic loaders ───────────────────────────────────────────────────────

async function loadTestsIndex() {
  if (_TESTS_CACHE !== null) return _TESTS_CACHE;
  try {
    const r = await fetch("/tests/index.json", { cache: "no-cache" });
    if (!r.ok) {
      _TESTS_CACHE = [];
      return _TESTS_CACHE;
    }
    _TESTS_CACHE = await r.json();
  } catch (e) {
    _TESTS_CACHE = [];
  }
  return _TESTS_CACHE;
}

async function loadSeriesIndex() {
  if (_SERIES_CACHE !== null) return _SERIES_CACHE;
  await loadTestsIndex();
  // Group tests by series_url
  const bySeries = {};
  for (const t of _TESTS_CACHE) {
    const key = t.series_url || (t.platform + "/" + t.slug);
    if (!bySeries[key]) {
      bySeries[key] = {
        id: seriesIdFor(t.platform, t.slug),
        platform: t.platform,
        slug: t.slug,
        name: t.series_name || (t.platform + "/" + t.slug),
        source_url: seriesUrlFor(t.platform, t.slug),
        tier: t.platform === "tb-pro" ? "Pro" : "Free",
        language: "English, Hindi",
        category: t.platform === "gd" ? "Guidely" : (t.platform === "tb-pro" ? "Pro" : "Free"),
        accent_color: "#16a34a",
        tint_color: "#dcfce7",
        sections: [],
        total_tests: 0,
      };
    }
    bySeries[key].total_tests++;
    // Add to a single "All Tests" section
    let sec = bySeries[key].sections.find(s => s.name === "All Tests");
    if (!sec) {
      sec = { name: "All Tests", test_count: 0, duration_minutes: 60, marks: 200, questions: 100, language: "English, Hindi", tests: [] };
      bySeries[key].sections.push(sec);
    }
    sec.tests.push({
      id: t.test_id,
      name: t.title,
      duration: t.duration_minutes || 60,
      marks: t.total_marks || 200,
      questions: t.question_count || (t.questions ? t.questions.length : 100),
      free: t.is_free || true,
    });
    sec.test_count++;
  }
  _SERIES_CACHE = Object.values(bySeries).sort((a, b) => b.total_tests - a.total_tests);
  return _SERIES_CACHE;
}

// ─── Public API (used by router.js) ────────────────────────────────────────

async function getAllSeriesAsync() {
  return await loadSeriesIndex();
}

function getAllSeries() {
  // Synchronous version — returns cached value (may be empty on first render)
  return _SERIES_CACHE || [];
}

function getSeriesById(id) {
  if (!_SERIES_CACHE) return null;
  return _SERIES_CACHE.find(s => s.id === id) || null;
}

async function getSeriesByIdAsync(id) {
  await loadSeriesIndex();
  return getSeriesById(id);
}
